version: '3.1'

services:
  app:
    build:
      context: '.'
      dockerfile: './docker/app/Dockerfile'
    depends_on:
      - db
    ports:
      - 8181:8080

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: touk
      POSTGRES_DB: touk
    ports:
      - 5555:5432

  tester:
    build:
      context: ./docker/tester
