spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/touk
    username: postgres
    password: touk
    hikari:
      data-source-properties: stringtype=unspecified

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    mapping-resources:
      - hibernate/mapping/Movie.hbm.xml
      - hibernate/mapping/Reservation.hbm.xml
      - hibernate/mapping/Screening.hbm.xml
      - hibernate/mapping/ScreeningRoom.hbm.xml
      - hibernate/mapping/Ticket.hbm.xml
      - hibernate/mapping/Voucher.hbm.xml



